### PR TITLE
Load Subjects Button

### LINKED ISSUE #12: 22-frontend-LoadSubjects
- [x] Add "Load Subjects" button and subjects table to page

- [x] The Admin menu should now have a "Load Subjects" page.

On this page, put the table of UCSB Subjects.

- [x] Add a button that will invoke the POST method of the backend to load subjects. The page should refresh, and there should be a toast saying how many new subjects were loaded (if any). 
- [x] If none (because they were all already there) the toast should say that.

### PR DESCRIPTION
**Pull request by edisonnchen**
# Overview

In this PR, we add a Load Subjects button that updates the Load Subject table with the proper subjects with a POST to the backend. This branch was branched from Robert's branch rh-21. ~~Not sure if it's best to merge into his branch or merge into main.~~ EDIT: Since Robert's branch was merged into main, I changed the branch to merge into main. May need a redeploy.

# Issues Addressed

Closes #12 

# Details

- When clicking on Load Subjects, the table should update with subjects stored on the database without a full reload. 
- There will be a toast with the proper amount of subjects retrieved
- When clicking on the button again when no new subjects have added, the toast should notify the admin accordingly
- I have changed the title of the page to Subjects from Load Subject. I think it makes more sense as a title and also the testing framework was picking up both the title "Load Subjects" and the button "Load Subjects" and was getting confused as to which element to select
- I have properly updated the stories to show both the page and table components, it was previously titled loadSubjectsPage but was the story for the table component

### CODE REVIEW

**Review by AHuangHe — DISMISSED** [review]
LGTM

**Review by Wenjin09 — COMMENTED** [review]
image
LGTM working on Heroku-QA

**Comment by Wenjin09** [comment]
# Update fixing the error 500 code
https://team04-w22-7pm-2.herokuapp.com/admin/UCSBSubjects:
When clicked on the bottom:
image

https://team04-w22-7pm-2-qa.herokuapp.com/admin/UCSBSubjects:
When clicked on the bottom:
image

**Review by tai-jui — APPROVED** [review]
LGTM!

**Pull request merged**
