### PR TITLE
PersonalSchedule table and form components as well as create and list pages

### LINKED ISSUE #25: Table component for PersonalSchedules
# Table component for PersonalSchedules

Using the Todos component as a model, create a similar component for PersonalSchedules.

## ACs

- [x]  The table has columns for database fields (i.e. the attributes of the corresponding @Entity class
- [x]  There is a `PersonalScheduleUtils` that contains a callback function for table delete
- [x]  There are fixtures under /frontend/src/fixtures for this data type, similar to the other fixtures files.
- [x]  There is a storybook entry similar to the one for Todos
- [x]  100% coverage with npm run coverage
- [x]  100% coverage with npx stryker run

### LINKED ISSUE #26: Implement List page for PersonalSchedules
Implement List page for PersonalSchedule

Implement the List page using the Table component made in a previous issue. 
You may use the TodosIndexPage as a model.

## ACs
- [x]  When loading the page, it fetches data from the backend and populates the table, if the role is User, it populates the table with only the user's personal schedules. If the role is admin, it shows everyone's personal schedule, with an additional column that displays the user id.
- [x] There are edit and delete columns that will be implemented in a later issue
- [x]  test coverage is 100% for npm run coverage
- [x]  test coverage is 100% for npx stryker run

### LINKED ISSUE #27: Make a form for PersonalSchedule to allow data entry
# Make a form for PersonalSchedule to allow data entry

Model your form after UCSBDateForm

- [x]  There is a form component under `frontend/src/main/components/PersonalSchedule/PersonalScheduleForm`
- [x]  That component has appropriate fields that match those in the database table
- [x]  There is data validation appropriate to the various fields
- [x]  There is a storybook entry that shows how the form works.
- [x]  There is 100% test coverage from npm run coverage
- [x]  There is 100% test coverage from npm run coverage and npx stryker run

### PR DESCRIPTION
**Pull request by tai-jui**
# Overview

This PR implements many front end components and pages for PersonalSchedule:
- PersonalSchedule table that renders data and button columns conditionally based on user type
- PersonalSchedule table have delete and edit buttons, with delete functionality implemented
- PersonalSchedule form that can be repurposed for both create and edit functionality
- PersonalSchedule create page that uses the form, with data validation
- PersonalSchedule index page that makes conditional calls to the backend depending on user type
- Added storybook stories for form and table (pages stories are implemented in #24)
- Includes personaSchedulesFixtures for storybook and testing
- Complete test coverage and mutation testing.

EDIT: We are aware of several permission issues that are being fixed on PR #39 

# Issues Addressed

Closes #27: Make a form for PersonalSchedule to allow data entry
Closes #26: Implement List page for PersonalSchedules
Closes #25: Table component for PersonalSchedules

# Details

NOTE: Edit functionality is not implemented within this PR

CleanShot 2022-03-11 at 10 31 09

CleanShot 2022-03-11 at 10 32 40

### CODE REVIEW

**Comment by Wenjin09** [comment]
we still have a few mutations that need to be solved(should be quick), we just pull whatever we leave for last night and will continue work on it tmr

**Review by bobhe9606 — DISMISSED** [review]
LGTM

**Comment by Wenjin09** [comment]
testing on Heroku:
image
image

**Review by Wenjin09 — DISMISSED** [review]
LGTM

**Comment by edisonnchen** [comment]
Going to split it into multiple PRs

**Pull request closed without merging**
