### PR TITLE
Edit page for PersonalSchedule

### LINKED ISSUE #28: Edit for PersonalSchedule
Edit for PersonalSchedule

Look at the edit logic in UCSBDateForm, UCSBDateIndexPage, and UCSBDateEditPage and model your edit logic accordingly.

- [x] There is a page component for edit
- [x]  In App.js a route is set up to route to the edit page with a param for the id (e.g. /collegiatesubreddits/edit/:id)
- [x]  When routing to the edit page, the form is pre-filled with the values for that record
- [x]  Clicking the cancel button reroutes to the list page, with the database unchanged.
- [x]  There is 100% test coverage from npm run coverage
- [x]  There is 100% test coverage from npx stryker run

### PR DESCRIPTION
**Pull request by tai-jui**
# Overview

In this PR, we solved some permission issues that were present on PR #37. We made sure that the admin had privileges to edit everyone schedules while users can only edit their own.

Additionally we overhauled the user permissions for API requests to fit the epic description, such that users can now perform create and delete operations.

# Issues Addressed

Closes #28 

# Details
CleanShot 2022-03-11 at 14 10 03

- AppNavbar has been changed to allow users to see the table
- Edit Page has been updated to reflect the updated user permission. Since admins and users have different calls to the backend, conditional statements were implemented
- Tests were updated to test both user and admin abilities

### CODE REVIEW

**Review by alvin0220 — DISMISSED** [review]
LGTM

**Review by edisonnchen — APPROVED** [review]
LGTM!!

**Review by edisonnchen — CHANGES_REQUESTED** [review]
When testing on Heroku, there is a backend error when you try to edit the existing schedules that were already loaded. However, you can create a schedule and edit that fine. The screenshot is right after clicking edit on the existing schedules.

image

**Comment by edisonnchen** [comment]
Appears to be a user permission error

**Review by Wenjin09 — DISMISSED** [review]
Testing on Heroku, working properly:
image

**Review by AHuangHe — DISMISSED** [review]
LGTM

**Review by AHuangHe — DISMISSED** [review]
LGTM

**Pull request merged**
