### PR TITLE
created placeholder UCSBSubjects table (frontend)

### LINKED ISSUE #11: 21-frontend-UCSBSubjects-Table copy
- [x] Add "Load Subjects" to admin menu

- [x] To the Admin menu, add a "Load Subjects" page.

- [x] Be sure the page has storybook and test coverage.

- [x] For now, the page is just a placeholder.

### PR DESCRIPTION
**Pull request by bobhe9606**
# Overview

Implemented a UCSBSubjects Table placeholder for the frontend. Awaiting backend code to be able to implement different functionalities for the table.

# Issues Addressed
Closes #11 

# Details

- Added another DropDown Item in the Admin section of the Navbar called "Load Subjects"
- Created a page with a placeholder table within the Load Subjects tab that will populate all the subjects we currently have
- Created tests for crashing for empty table and 3 subjects parameters. In addition to seeing if the table have expected column headers and content

### CODE REVIEW

**Review by btk5h — DISMISSED** [review]
Hi, there are too many files in this PR that should not be committed. Please clean up any OS-specific/temporary files from this PR before requesting a review.

**Comment by edisonnchen** [comment]
Add a .gitignore for stryker or set it as a temp directory in stryker and it will autodelete after mutation testing.

**Review by AHuangHe — DISMISSED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
Deleting the .env.SAMPLE file is NOT a change we want to make.  
Please restore that file on this branch; it is not mergable without that change.

**Review by pconrad — CHANGES_REQUESTED** [review]
Title is a bit ambiguous: created placeholder table for what?  I should be able to glance at the title and know what it refers to.   There could be many tables in this app, so we need something a bit more specfic.

In addition the description of the PR is currently the *template text* that tells you how to write a PR description.  Please follow those instructions, and replace that template text with a reasonable PR description.

If you need examples, ask and I can link to you a few.

**Comment by bobhe9606** [comment]
> Title is a bit ambiguous: created placeholder table for what? I should be able to glance at the title and know what it refers to. There could be many tables in this app, so we need something a bit more specfic.
> 
> In addition the description of the PR is currently the _template text_ that tells you how to write a PR description. Please follow those instructions, and replace that template text with a reasonable PR description.
> 
> If you need examples, ask and I can link to you a few.

**Review by AHuangHe — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM... waiting on CI/CD to finish

**Pull request merged**
