### PR TITLE
Implemented menu bar items and page components placeholders for PersonalSchedule

### LINKED ISSUE #24: Add PersonalSchedule menu and page placeholders
# Add PersonalSchedule menu and page placeholders

The menu shows up only when logged in. There are two links for both users and admins, List and Create These links go to placeholder pages PersonalScheduleIndexPage and PersonalScheduleCreatePage.

## Navbar related Acceptance Criteria

- [x]  There is a menu item PersonalSchedule (this is done on the Navbar)
- [x]  The menu item on the navbar only shows up when you are logged in.
- [x]  It has two items for Admins and User: List and Create
- [x]  List routes to /personalschedule/list
- [x]  Create routes to /personalschedule/create

## Page related acceptance criteria

- [x]  There are pages components under /frontend/src/main/pages/PersonalSchedule/ similar to those under /frontend/src/main/pages/Todos/ for the create and index pages.
- [x]  There are entries for these pages in the storybook.
- [x]  The List placeholder page is available at /personalschedule/list (this is done in App.js)
- [x]  The Create placeholder page is available at /personalschedule/create (this is done in App.js)

### PR DESCRIPTION
**Pull request by alvin0220**
# Overview

In this PR I Implemented menu place holder and page components for Personal schedule, tested on local host file. #24

### CODE REVIEW

**Review by tai-jui — DISMISSED** [review]
Reviewed live through screenshare. ~~Test coverage will be implemented later in other issues~~. Tests need to be implemented now for full code coverage.

**Review by bobhe9606 — COMMENTED** [review]
Need test for AppNavbar.js and resolve conflicts

**Comment by tai-jui** [comment]
Spent 30 minutes in rebase purgatory. I hard forced to a previous commit and try to build it back incrementally. There doesn't seem to be merge conflicts, and I made sure both App.js and NavBar.js have the necessary changes.

**Review by edisonnchen — DISMISSED** [review]
LGTM but what is text.txt for?

**Comment by tai-jui** [comment]
> LGTM but what is text.txt for?

I have deleted it

**Review by bobhe9606 — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM--will try to merge after deployment on Heroku

**Pull request merged**
